site_name: PepperDocs
site_description: Pepper Care Instructions
site_author: adamkoziol

# Directory containing the documentation source files
docs_dir: 'docs'

theme:
  name: 'readthedocs'
  favicon: 'images/favicon.ico'

# Navigation structure
nav:
  - Home: 'index.md'
  - Hot Peppers:
    - 7 Pot Congo Chocolate: "7_pot_congo_chocolate.md"
    - Adrenalina: "adrenalina.md"
    - Blood Ghost: "blood_ghost.md"
    - Carolina Reaper: "carolina_reaper.md"
    - Da Hulk: "da_hulk.md"
    - Death Spiral: "death_spiral.md"
    - Jamaican Scotch Bonnet: "jamaican_scotch_bonnet.md"
    - Leviathan Scorpion Chocolate: "leviathan_scorpion_chocolate.md"
    - Naga Tiger DD: 'naga_tiger_dd.md'
    - Orange Habanero: 'orange_habanero.md'
    - Reaper Pink Peach: "reaper_pink_peach.md"
    - T-Rex Mustard: "t-rex_mustard.md"
    - Trinidad Moruga Scorpion: "trinidad_moruga_scorpion.md"
    - White Habanero: "white_habanero.md"
    - Yellow Fatalii: "yellow_fatalii.md"
  - Medium Peppers:
    - Aji White Fantasy: "aji_white_fantasy.md"
    - Aji White Lightning Bolt: 'aji_white_lightning_bolt.md'
    - Cayenne: "cayenne.md"
    - Chinese Five Colour: "chinese_five_colour.md"
    - Count Dracula: "count_dracula.md"
    - Thai Dragon: "thai_dragon.md"
  - Sweet Peppers:
    - Cubanelle: "cubanelle.md"
    - Gatherer’s Gold: "gatherers_gold.md"
    - Georgescu Chocolate: "georgescu_chocolate.md"
    - HMS Orange Picnic: "HMS_orange_picnic.md"
    - HMS Yellow Picnic: "HMS_yellow_picnic.md"
    - Shepherd: "shepherd.md"
